# mode_ci:
#   enabled: true # default is false
#   branch: 'production' # default is master
# branch: 'production' # default is master
# path: '/tmp/mycustompath' # Set path where report will be saved (tmp/rubycritic by default)
threshold_score: 10 # default is 0
deduplicate_symlinks: true # default is false
# suppress_ratings: true # default is false
# no_browser: true # default is false
# formats: # Available values are: html, json, console, lint. Default value is html.
#   - console
minimum_score: 70 # default is 0
paths: # Files to analyse.
  - 'app/concerns/'
  - 'app/controllers/'
  - 'app/helpers/'
  - 'app/mailers/'
  - 'app/models/'
