require:
  - rubocop-rails

AllCops:
  NewCops: enable
  # SuggestExtensions: false  

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - Guardfile

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 110

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  Enabled: true