version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

  db:
    image: sqlite:latest
    volumes:
      - ./db:/db
